query GetCirclesAccountsByaddress($address: String!, $expirationTime: BigInt!) {
  registrations(where: { claimer: $address , expirationTime_gt: $expirationTime }) {
    id
    circleAccount {
      id               # the circles‐account address
      trustExpiryTime  
    }
  }

  crossChainRegistrations(where: { claimer: $address , expirationTime_gt: $expirationTime }) {
    id
    circleAccount {
      id
      trustExpiryTime
    }
  }
}